<a href="https://colab.research.google.com/github/Zulfatinnafisah/Kumpulan-Tugas-Kampus-Merdeka/blob/main/Tugas_week_VIII_Numpy_Preprocessing_Zulfatin_Nafisah.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Tugas Numpy Week 8**

1.) Buatlah sebuah array dari nilai random antara 10-100 dengan ukuran 1x60
Tentukan nilai berikut:
- Ubah ukuran array tersebut menjadi 6x10
- Transpose array baru di atas
- Dari hasil transpose, Temukan elemen dengan nilai di bawah 50, dan ganti elemen tersebut
dengan nilai 50

In [52]:
#import library numpy
import numpy as np

In [53]:
#membuat array dengan nilai random antara 10-100 dengan ukuran 1x60
array =np.random.randint(10,100, size=60)
print(array)

[60 67 57 75 75 81 37 42 52 34 34 80 86 87 82 35 32 24 30 46 11 80 57 70
 35 70 38 79 86 86 92 62 52 67 99 36 40 18 40 62 58 62 42 38 74 83 67 53
 84 28 47 31 97 83 23 22 31 97 43 10]


In [54]:
#mengubah ukuran array menjadi 6x10
newarray = np.reshape(array, (6, 10))
print(newarray)

[[60 67 57 75 75 81 37 42 52 34]
 [34 80 86 87 82 35 32 24 30 46]
 [11 80 57 70 35 70 38 79 86 86]
 [92 62 52 67 99 36 40 18 40 62]
 [58 62 42 38 74 83 67 53 84 28]
 [47 31 97 83 23 22 31 97 43 10]]


In [55]:
#mentranspose array baru
newarray_transpose = np.transpose(newarray)
print(newarray_transpose)

[[60 34 11 92 58 47]
 [67 80 80 62 62 31]
 [57 86 57 52 42 97]
 [75 87 70 67 38 83]
 [75 82 35 99 74 23]
 [81 35 70 36 83 22]
 [37 32 38 40 67 31]
 [42 24 79 18 53 97]
 [52 30 86 40 84 43]
 [34 46 86 62 28 10]]


In [56]:
#menemukan elemen dengan nilai dibawah 50 dan mengganti elemen tersebut dengan nilai 50
np.where(newarray_transpose < 50, 50, newarray_transpose)

array([[60, 50, 50, 92, 58, 50],
       [67, 80, 80, 62, 62, 50],
       [57, 86, 57, 52, 50, 97],
       [75, 87, 70, 67, 50, 83],
       [75, 82, 50, 99, 74, 50],
       [81, 50, 70, 50, 83, 50],
       [50, 50, 50, 50, 67, 50],
       [50, 50, 79, 50, 53, 97],
       [52, 50, 86, 50, 84, 50],
       [50, 50, 86, 62, 50, 50]])

2.) Buatlah array1 dari nilai random normal ukuran 1 x 20

Buatlah array2 yang berisi 20 elemen dengan jarak yang sama antara 1 sampai 100
Tentukan nilai berikut:
- Gabungkan kedua array tersebut dengan penggabungan vertikal dan horizontal
- Dari penggabungan secara horizontal, temukan elemen dengan nilai di atas 60, dan ganti
elemen tersebut dengan nilai 0

In [57]:
#membuat array1 dari nilai random normal ukuran 1 x 20
array1 = np.random.randint(0, 100, size = 20)
print(array1)

[ 0 31 40  0  0 92 85 66 65 18  8 10 29 54 59 91 15 55 10 51]


In [58]:
#membuat array2 yang berisi 20 elemen dengan jarak yang sama antara 1 sampai 100
array2 = np.linspace(1,100,20)
print(array2)

[  1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  73.94736842
  79.15789474  84.36842105  89.57894737  94.78947368 100.        ]


In [59]:
#menggabungkan array1 dan array2 dengan penggabungan vertikal dan horizontal 

#Penggabungan secara vertikal
v_arr=np.column_stack([array1, array2])
print(v_arr)

#Penggabungan secara horizontal
h_arr=np.concatenate([array1, array2])
print(h_arr)

[[  0.           1.        ]
 [ 31.           6.21052632]
 [ 40.          11.42105263]
 [  0.          16.63157895]
 [  0.          21.84210526]
 [ 92.          27.05263158]
 [ 85.          32.26315789]
 [ 66.          37.47368421]
 [ 65.          42.68421053]
 [ 18.          47.89473684]
 [  8.          53.10526316]
 [ 10.          58.31578947]
 [ 29.          63.52631579]
 [ 54.          68.73684211]
 [ 59.          73.94736842]
 [ 91.          79.15789474]
 [ 15.          84.36842105]
 [ 55.          89.57894737]
 [ 10.          94.78947368]
 [ 51.         100.        ]]
[  0.          31.          40.           0.           0.
  92.          85.          66.          65.          18.
   8.          10.          29.          54.          59.
  91.          15.          55.          10.          51.
   1.           6.21052632  11.42105263  16.63157895  21.84210526
  27.05263158  32.26315789  37.47368421  42.68421053  47.89473684
  53.10526316  58.31578947  63.52631579  68.73684211  7

In [60]:
#menemukan elemen dengan nilai di atas 60 dan mengganti elemen tersebut dengan nilai 0 pada penggabungan horizontal
print(np.where(h_arr > 60,0, h_arr))

[ 0.         31.         40.          0.          0.          0.
  0.          0.          0.         18.          8.         10.
 29.         54.         59.          0.         15.         55.
 10.         51.          1.          6.21052632 11.42105263 16.63157895
 21.84210526 27.05263158 32.26315789 37.47368421 42.68421053 47.89473684
 53.10526316 58.31578947  0.          0.          0.          0.
  0.          0.          0.          0.        ]


3.) Import data menggunakan file “Lending-Company-Numeric-Data.csv”
dan hanya tampilkan kolom dengan indeks ke 1,2, dan 3

Hitunglah mean dari setiap kolom tersebut !

In [61]:
#mengimport data dan menampilkan kolom dengan indeks ke 1, 2, dan 3
lending_data = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
print(lending_data[:3])

#menghitung mean dari setiap kolom
lending_data_mean = np.nanmean(lending_data, axis = 0).round(2)
print(lending_data_mean)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]]
[ 2257.43    46.09   365.    3926.74  5181.   16618.91]


4.) Import data menggunakan file “Lending-company-Numeric-NAN.csv”
- Hitunglah jumlah NAN dari semua elemen di data tersebut
- Hitunglah jumlah NAN dari setiap kolom di data tersebut

Note:

dapat menggunakan sum(axis=)

In [63]:
#Mengimport data dan menampilkan isi dari data tersebut
lending_nan = np.genfromtxt("Lending-company-Numeric-NAN.csv", delimiter = ';')
print(lending_nan)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [   nan    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [64]:
#menghitung jumlah NAN dari semua elemen 
np.isnan(lending_nan).sum()

260

In [65]:
#menghitung jumlah NAN dari setiap kolom
print(np.isnan(lending_nan).sum(axis = 0))

[34 48 52 62 38 26]


5.) Import data menggunakan file “Lending-Company-Numeric-Data.csv”
- Hitunglah elemen unik dari kolom pertama di data tersebut (keluarkan juga jumlah element
untuk setiap elemen unik tersebut)
- Delete kolom ke-2 dan ke-6 dari data tersebut dan simpan menjadi data_2
- hitung nilai rata-rata dari data_2

In [66]:
#Mengimport data dan menampilkan isi dari data tersebut
company_data = np.genfromtxt("Lending-Company-Numeric-Data.csv", delimiter = ',')
print(company_data)

[[ 2000.    40.   365.  3121.  4241. 13621.]
 [ 2000.    40.   365.  3061.  4171. 15041.]
 [ 1000.    40.   365.  2160.  3280. 15340.]
 ...
 [ 2000.    40.   365.  4201.  5001. 16600.]
 [ 1000.    40.   365.  2080.  3320. 15600.]
 [ 2000.    40.   365.  4601.  4601. 16600.]]


In [67]:
#menghitung elemen unik dari kolom pertama
print(np.unique(company_data[:,0]))

#Menghitung jumlah elemen unik
print(len(np.unique(company_data[:,0])))

[1000. 2000. 2500. 4000. 9000.]
5


In [68]:
#menghapus kolom ke-2 dan ke-6
data_2 = np.delete(company_data, [1,5] , axis = 1)
print(data_2)

[[2000.  365. 3121. 4241.]
 [2000.  365. 3061. 4171.]
 [1000.  365. 2160. 3280.]
 ...
 [2000.  365. 4201. 5001.]
 [1000.  365. 2080. 3320.]
 [2000.  365. 4601. 4601.]]


In [70]:
#menghitung nilai rata-rata dari data_2
np.nanmean(company_data).round(2)

4732.53